name = "infogap"
compatibility_date = "2025-06-01"

[vars]
LINKEDIN_CLIENT_ID = "86syymbfnmyxcp"

[[d1_databases]]
binding = "DB"
database_name = "infogap"
database_id = "3e27bdd5-341f-445f-8c35-63be5fe7fe27"
